name: Java CI Unittest

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.14'
          distribution: 'temurin'
      - name: Test with Maven
        run: mvn test
